//! Label stability and orphan-reconciliation tests for OCI lifecycle.
//!
//! Tests that caduceus labels are stable across multiple executor runs,
//! labels on the state row match runtime labels, and labels are
//! queryable via docker/podman filter (integration tests, ignored
//! on hosts without an OCI engine).

use std::path::{Path, PathBuf};

use caduceus::executor::sandbox_renderer::render;
use caduceus::executor::sandbox_spec::{resolve, SandboxEngine, SandboxSpec};
use caduceus::executor::ExecutorSpec;
use caduceus::github::issue::IssueKey;
use caduceus::infra::config::Config;

mod support;

fn test_cfg() -> Config {
    Config::test_defaults(Path::new("/tmp"))
}

fn resolve_from(cfg: &Config, run_id: &str) -> SandboxSpec {
    let worktree = cfg.workdir_base.join("owner").join("repo").join(run_id);
    let runtime = support::runtime_facts(cfg, run_id, &worktree);
    resolve(cfg.sandbox(), &runtime, &support::executor_spec(&runtime)).expect("must resolve")
}

// stable_labels_across_calls (AC-05)

/// Labels produced by two `OciExecutor::run` calls with the same
/// daemon_id must be stable.
#[test]
fn stable_labels_across_calls() {
    let cfg = test_cfg();

    let spec_a = resolve_from(&cfg, "label-run-001");
    let spec_b = resolve_from(&cfg, "label-run-002");

    let argv_a = render(&spec_a, SandboxEngine::Docker);
    let argv_b = render(&spec_b, SandboxEngine::Docker);
    let labels_a: Vec<&String> = argv_a
        .iter()
        .filter(|t| t.starts_with("caduceus."))
        .collect();
    let labels_b: Vec<&String> = argv_b
        .iter()
        .filter(|t| t.starts_with("caduceus."))
        .collect();

    // daemon_id must be identical
    let daemon_a: Vec<&&String> = labels_a
        .iter()
        .filter(|l| l.starts_with("caduceus.daemon_id"))
        .collect();
    let daemon_b: Vec<&&String> = labels_b
        .iter()
        .filter(|l| l.starts_with("caduceus.daemon_id"))
        .collect();
    assert_eq!(
        daemon_a, daemon_b,
        "daemon_id label must be identical across runs"
    );

    // run_id must differ
    let run_a: Vec<&&String> = labels_a
        .iter()
        .filter(|l| l.starts_with("caduceus.run_id"))
        .collect();
    let run_b: Vec<&&String> = labels_b
        .iter()
        .filter(|l| l.starts_with("caduceus.run_id"))
        .collect();
    assert_ne!(run_a, run_b, "run_id labels must differ");

    // issue_id must be identical (same issue key)
    let issue_a: Vec<&&String> = labels_a
        .iter()
        .filter(|l| l.starts_with("caduceus.issue_id"))
        .collect();
    let issue_b: Vec<&&String> = labels_b
        .iter()
        .filter(|l| l.starts_with("caduceus.issue_id"))
        .collect();
    assert_eq!(
        issue_a, issue_b,
        "issue_id must be identical for same issue"
    );
}

// labels_persist_in_state_row (AC-05)

/// Labels on the state row match the runtime labels generated by the
/// renderer.
#[test]
fn labels_persist_in_state_row() {
    use caduceus::state::oci_run::{ContainerRunRow, OciLifecycleState};

    let cfg = test_cfg();
    let spec = resolve_from(&cfg, "label-row-001");
    let argv = render(&spec, SandboxEngine::Docker);

    // Extract labels from argv
    let daemon_label = argv
        .iter()
        .find(|t| t.starts_with("caduceus.daemon_id="))
        .expect("must have daemon_id label");
    let run_label = argv
        .iter()
        .find(|t| t.starts_with("caduceus.run_id="))
        .expect("must have run_id label");
    let issue_label = argv
        .iter()
        .find(|t| t.starts_with("caduceus.issue_id="))
        .expect("must have issue_id label");

    // Build a state row that matches what the lifecycle would insert
    let row = ContainerRunRow {
        run_id: "label-row-001".to_string(),
        container_id: Some("abc123".to_string()),
        state: OciLifecycleState::Created,
        engine: "Docker".to_string(),
        created_at: "2026-01-01T00:00:00Z".to_string(),
        updated_at: "2026-01-01T00:00:00Z".to_string(),
        daemon_id: daemon_label
            .strip_prefix("caduceus.daemon_id=")
            .unwrap()
            .to_string(),
        issue_id: issue_label
            .strip_prefix("caduceus.issue_id=")
            .unwrap()
            .to_string(),
        worker_command_sha256: "abc".to_string(),
    };

    // The row's daemon_id must match the runtime label's value
    assert_eq!(
        row.daemon_id,
        daemon_label.strip_prefix("caduceus.daemon_id=").unwrap()
    );

    // The row's run_id must match the runtime label's value
    assert_eq!(
        row.run_id,
        run_label.strip_prefix("caduceus.run_id=").unwrap()
    );

    // The row's issue_id must match the runtime label's value
    assert_eq!(
        row.issue_id,
        issue_label.strip_prefix("caduceus.issue_id=").unwrap()
    );
}

// labels_queryable_via_filter (AC-05)

/// Labels are queryable via `docker ps --filter label=caduceus.run_id=<id>`.
/// This test requires Docker to be running and is ignored on hosts
/// without Docker.
#[test]
#[ignore = "requires docker running"]
fn labels_queryable_via_filter() {
    use std::process::Command;

    let cfg = test_cfg();
    let spec = resolve_from(&cfg, "label-filter-001");
    let argv = render(&spec, SandboxEngine::Docker);

    let run_label = argv
        .iter()
        .find(|t| t.starts_with("caduceus.run_id="))
        .expect("must have run_id label");

    // Extract the label value
    let run_id_value = run_label.strip_prefix("caduceus.run_id=").unwrap();

    // Query docker for containers with this label
    let filter = format!("label=caduceus.run_id={run_id_value}");
    let output = Command::new("docker")
        .args(["ps", "-a", "--filter", &filter, "--format", "{{.ID}}"])
        .output();

    // If docker is available and the filter is well-formed, the command
    // should exit successfully (0 containers found is OK — we're just
    // testing the label filter syntax).
    match output {
        Ok(out) => {
            let stdout = String::from_utf8_lossy(&out.stdout);
            assert!(
                !stdout.contains("Error"),
                "docker ps filter failed: {stdout}"
            );
        }
        Err(_) => {
            // docker not installed — the ignore annotation should
            // prevent this test from running, but if it still does,
            // this is not a test failure.
            eprintln!("docker not available — skipping label filter test");
        }
    }
}

// Compile-time sanity: ExecutorSpec still exists untouched (the
// daemon-facing input consumed by OciExecutor::run).

#[test]
fn executor_spec_surface_intact() {
    let _ = ExecutorSpec {
        self_exe: PathBuf::from("/usr/bin/caduceus"),
        target: caduceus::executor::WorkTarget::Issue(caduceus::executor::IssueWorkTarget {
            key: IssueKey::parse("owner/repo#1").expect("valid key"),
            title: "title".to_string(),
            body: "body".to_string(),
            labels: Vec::new(),
            branch_name: "automation/issue-1".to_string(),
        }),
        worktree: PathBuf::from("/tmp/worktree"),
        run_id: "surface-001".to_string(),
        context_json: r#"{"x":1}"#.to_string(),
        worker_command: vec!["python3".to_string(), "bridge.py".to_string()],
        cancellation: tokio_util::sync::CancellationToken::new(),
    };
}
