"""Pulse wrapper template/comment tests."""

from __future__ import annotations

import json
import os
import re
import shutil
import stat
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List

import pytest

from tests.fixtures.fake_ctx import (
    FakePluginContext,
    assert_cli_command_registered,
    assert_command_registered,
    assert_skill_registered,
)


def test_write_pulse_wrapper_no_misleading_comments(
    adapter, install_with_fake_binary: Path, isolated_hermes_home: Path
) -> None:
    """_write_pulse_wrapper no longer has misleading comments (AC-12)."""
    # We check the body content the adapter generates.
    # Get the source of the function.
    import inspect
    source = inspect.getsource(adapter._write_pulse_wrapper)
    # The body string should not contain "Generated by" (the old comment
    # was misleading — it's generated at runtime with the installed path).
    # Actually AC-12 says REMOVE misleading comments, so let's verify
    # the body is clean.
    assert "Do not edit by hand" not in source
    # The wrapper should still contain the exec line and set -euo pipefail.
    body = (
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n"
        f"exec {install_with_fake_binary} run \"$@\"\n"
    )
    # The generated wrapper should match a clean structure.
    adapter._write_pulse_wrapper(install_with_fake_binary)
    wrapper_path = isolated_hermes_home / "scripts" / "caduceus-pulse.sh"
    assert wrapper_path.is_file()
    text = wrapper_path.read_text(encoding="utf-8")
    assert text == body




def test_pulse_template_has_strict_shell_and_accurate_comments(
    plugin_root: Path
) -> None:
    """caduceus-pulse.sh has strict shell and accurate comments (AC-12)."""
    template = plugin_root / "plugin-assets" / "caduceus-pulse.sh"
    text = template.read_text(encoding="utf-8")
    lines = text.splitlines()

    # Must have strict shell settings.
    assert "set -euo pipefail" in text
    # Must NOT have misleading or dev-only comments.
    assert "FIXME" not in text
    assert "TODO" not in text
    assert "pending" not in text.lower()
    assert "dev-only" not in text.lower()
    # Must accurately describe what the file is.
    assert "template" in text.lower() or "Template" in text
