//! Typed error hierarchy for the daemon.
//!
//! [`CaduceusError`] is the canonical cross-cutting error type. It is
//! re-exported from `lib.rs` and used by every module. The variant
//! set and the field semantics are pinned by `CONTRACTS.md`
//! "Error contract".
//!
//! [`VoiceError`] is a separate type used by the public-voice
//! validator (Task 6.6). It is intentionally separate from
//! [`CaduceusError`] because the voice validator runs *before* the
//! corresponding API mutation and needs to surface a precise
//! reason; mixing the two would lose that distinction.
//!
//! `Debug` is wired through [`scrub`] so a resolved token can never
//! appear in a panic message, log line, or test failure. Callers
//! must pre-scrub before constructing an error variant — the
//! type's invariant is "no resolved token in any string field".

use std::fmt;
use std::path::PathBuf;

/// All Caduceus errors. The variant set is normative; new errors
/// always go through a `CaduceusError` constructor, never a panic on
/// external data.
///
/// `Debug` is wired through [`scrub`] so a resolved token can never
/// appear in user-visible output. `Display` is generated by
/// thiserror and renders variant fields verbatim — callers must
/// scrub before constructing. The daemon's structured logger and
/// the public-voice validator both pass through `Debug` only.
#[derive(thiserror::Error)]
pub enum CaduceusError {
    #[error("caduceus configuration error: {0}")]
    Config(String),

    #[error(transparent)]
    Io(#[from] std::io::Error),

    #[error(transparent)]
    Json(#[from] serde_json::Error),

    #[error(transparent)]
    Yaml(#[from] serde_yaml::Error),

    #[error(transparent)]
    Http(#[from] reqwest::Error),

    /// Git subprocess failure. The ``operation`` is a short stable
    /// identifier (e.g. ``"commit"``, ``"push"``); ``stderr`` carries
    /// the captured stderr text (already redacted by the caller).
    #[error("git {operation} failed: {stderr}")]
    Git {
        operation: &'static str,
        stderr: String,
    },

    /// GitHub API returned a non-success status.
    #[error("GitHub API status {status}: {message}")]
    GitHubApi { status: u16, message: String },

    /// GitHub rate-limit observation. The numeric ``reset_at`` is
    /// the seconds-until-reset reported by the API; ``remaining``
    /// is the request budget left; ``limit`` is the per-window cap
    /// (None when the API omits it).
    #[error("GitHub rate limited; reset in {reset_at}s (remaining {remaining}/{limit:?})")]
    RateLimited {
        reset_at: u64,
        remaining: u32,
        limit: Option<u32>,
    },

    /// Token resolution failure. The wrapped string is a reason
    /// (``"gh not found"``, ``"gh exited 1"``); never the token.
    #[error("failed to resolve a GitHub token: {0}")]
    TokenResolution(String),

    /// Worker supervision failure. ``context`` is a stable operation
    /// label (``"spawn"``, ``"wait"``, ``"signal"``); ``stderr``
    /// carries the captured error text (already redacted).
    #[error("worker supervision failure during {context}: {stderr}")]
    Worker {
        context: &'static str,
        stderr: String,
    },

    /// Worktree creation/teardown failure. ``context`` is a stable
    /// operation label (``"create"``, ``"destroy"``, ``"gc"``);
    /// ``stderr`` carries the captured error text.
    #[error("worktree {context} failure: {stderr}")]
    Worktree {
        context: &'static str,
        stderr: String,
    },

    /// Queue state transition failure. ``context`` is a stable
    /// operation label (``"claim"``, ``"release"``, ``"complete"``).
    #[error("queue {context} failure: {stderr}")]
    Queue {
        context: &'static str,
        stderr: String,
    },

    /// Push subprocess failure. ``context`` is a stable operation
    /// label (``"ls-remote"``, ``"push"``); ``stderr`` carries the
    /// captured error text (already redacted by the caller).
    #[error("push {context} failure: {stderr}")]
    Push {
        context: &'static str,
        stderr: String,
    },

    /// The remote had a non-ancestor ref under the daemon branch
    /// name. The push is rejected without `--force`; the operator
    /// must reconcile the branch manually.
    #[error("push collision on {branch}: remote {remote_oid}, local {local_oid}")]
    PushCollision {
        branch: String,
        remote_oid: String,
        local_oid: String,
    },

    /// State file is corrupt on disk. The path is preserved verbatim
    /// so the operator can quarantine or inspect the file. The
    /// error variant does NOT auto-delete the file — the daemon's
    /// contract preserves corruption for diagnosis.
    #[error("corrupt state file at {}: {message}", path.display())]
    StateCorrupt { path: PathBuf, message: String },

    #[error("operation cancelled")]
    Cancelled,

    #[error("{0}")]
    Other(String),
}

/// Canonical `Result` alias used everywhere in the daemon.
pub type CaduceusResult<T> = Result<T, CaduceusError>;

impl fmt::Debug for CaduceusError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // Render via Display, scrubbed through the redaction helper.
        // This keeps the contract guarantee: Debug never contains
        // a resolved token.
        let rendered = match self {
            CaduceusError::Config(s) => format!("Config({})", scrub(s)),
            CaduceusError::Io(err) => format!("Io({})", scrub(&err.to_string())),
            CaduceusError::Json(err) => format!("Json({})", scrub(&err.to_string())),
            CaduceusError::Yaml(err) => format!("Yaml({})", scrub(&err.to_string())),
            CaduceusError::Http(err) => format!("Http({})", scrub(&err.to_string())),
            CaduceusError::Git { operation, stderr } => {
                format!(
                    "Git {{ operation: {:?}, stderr: {} }}",
                    operation,
                    scrub(stderr)
                )
            }
            CaduceusError::GitHubApi { status, message } => format!(
                "GitHubApi {{ status: {status}, message: {} }}",
                scrub(message)
            ),
            CaduceusError::RateLimited {
                reset_at,
                remaining,
                limit,
            } => format!(
                "RateLimited {{ reset_at: {reset_at}, remaining: {remaining}, limit: {limit:?} }}"
            ),
            CaduceusError::TokenResolution(s) => {
                format!("TokenResolution({})", scrub(s))
            }
            CaduceusError::Worker { context, stderr } => format!(
                "Worker {{ context: {:?}, stderr: {} }}",
                context,
                scrub(stderr)
            ),
            CaduceusError::Worktree { context, stderr } => format!(
                "Worktree {{ context: {:?}, stderr: {} }}",
                context,
                scrub(stderr)
            ),
            CaduceusError::Queue { context, stderr } => format!(
                "Queue {{ context: {:?}, stderr: {} }}",
                context,
                scrub(stderr)
            ),
            CaduceusError::Push { context, stderr } => format!(
                "Push {{ context: {:?}, stderr: {} }}",
                context,
                scrub(stderr)
            ),
            CaduceusError::PushCollision {
                branch,
                remote_oid,
                local_oid,
            } => format!(
                "PushCollision {{ branch: {:?}, remote_oid: {:?}, local_oid: {:?} }}",
                branch, remote_oid, local_oid
            ),
            CaduceusError::StateCorrupt { path, message } => format!(
                "StateCorrupt {{ path: {:?}, message: {} }}",
                path,
                scrub(message)
            ),
            CaduceusError::Cancelled => "Cancelled".to_string(),
            CaduceusError::Other(s) => format!("Other({})", scrub(s)),
        };
        f.write_str(&rendered)
    }
}

impl CaduceusError {
    /// Wrap a non-token error message in `Other(String)`. This is
    /// the only public constructor that doesn't already have a
    /// variant; callers should prefer the typed variants.
    pub fn other<S: Into<String>>(message: S) -> Self {
        CaduceusError::Other(message.into())
    }

    /// Map a daemon error to the process exit code announced in
    /// `CONTRACTS.md` "CLI contract".
    ///
    /// `run` returns 0 for processed/idle/concurrent/cadence/
    /// rate-limit/cancelled outcomes and 1 for configuration,
    /// corruption, invariant, or unrecovered pipeline failures.
    /// `status` returns 2 for missing state and 1 for corrupt
    /// state. The CLI host code is responsible for selecting the
    /// right exit-code policy per command.
    pub fn exit_code(&self) -> std::process::ExitCode {
        use std::process::ExitCode;
        match self {
            CaduceusError::Cancelled => ExitCode::from(0),
            CaduceusError::RateLimited { .. } => ExitCode::from(0),
            _ => ExitCode::from(1),
        }
    }
}

// ---------------------------------------------------------------------------
// Voice errors
// ---------------------------------------------------------------------------

/// Errors produced by the public-voice validator (Task 6.6). Kept
/// separate from [`CaduceusError`] so the validator can run before
/// a corresponding API mutation has been attempted and report a
/// precise reason without conflating with daemon-wide errors.
#[derive(Clone, Debug, Eq, PartialEq, thiserror::Error)]
pub enum VoiceError {
    /// A configured forbidden term was found in the outbound text.
    /// The first match is captured — operators see *which* term
    /// was matched so they can update the allowlist.
    #[error("voice: forbidden term matched: {found:?}")]
    Forbidden { found: String },

    /// The outbound text exceeds the documented size limit for the
    /// channel (PR body, comment, etc.).
    #[error("voice: text exceeds limit of {limit} bytes")]
    TooLong { limit: usize },
}

impl VoiceError {
    /// True when the error is purely about the text content; the
    /// daemon can suppress retry on these and ask the operator to
    /// adjust the source text.
    pub fn is_terminal(&self) -> bool {
        match self {
            VoiceError::Forbidden { .. } => true,
            VoiceError::TooLong { .. } => true,
        }
    }
}

// ---------------------------------------------------------------------------
// Lossless conversions
// ---------------------------------------------------------------------------

impl From<std::path::StripPrefixError> for CaduceusError {
    fn from(_: std::path::StripPrefixError) -> Self {
        CaduceusError::Other("strip prefix failed".to_string())
    }
}

// `From<tokio::task::JoinError>` etc. would be added here as the
// runtime grows. Only conversions that lose no information about the
// underlying cause land in this impl block.

impl From<std::num::ParseIntError> for CaduceusError {
    fn from(err: std::num::ParseIntError) -> Self {
        CaduceusError::Other(format!("parse int: {err}"))
    }
}

// ---------------------------------------------------------------------------
// Redaction helper
// ---------------------------------------------------------------------------

/// Replace recognised credential names with `<redacted>` so the
/// returned string is safe to render through `Debug` (and any
/// downstream `tracing` panic message or test failure message).
///
/// The deny-list mirrors the worker-env-allowlist contract: the
/// three canonical credential variables and any prefix wildcard
/// that would expose them. The function is intentionally a
/// standalone helper so every error path that wants to surface a
/// string can apply it.
pub fn scrub(value: &str) -> String {
    if value.is_empty() {
        return value.to_string();
    }
    let mut scrubbed = value.to_string();
    for needle in ["GITHUB_TOKEN", "CADUCEUS_GITHUB_TOKEN", "GH_TOKEN"] {
        let mut search_from = 0usize;
        while let Some(pos) = scrubbed[search_from..].find(needle) {
            let abs = search_from + pos;
            // Boundary check on the left so ``MY_GITHUB_TOKEN`` is
            // not matched.
            if abs > 0 {
                let prev = scrubbed.as_bytes()[abs - 1];
                if prev.is_ascii_alphanumeric() || prev == b'_' {
                    search_from = abs + needle.len();
                    continue;
                }
            }
            let after = abs + needle.len();
            let mut cursor = after;
            while cursor < scrubbed.len() && scrubbed.as_bytes()[cursor] == b' ' {
                cursor += 1;
            }
            if cursor < scrubbed.len() && scrubbed.as_bytes()[cursor] == b'=' {
                cursor += 1;
                while cursor < scrubbed.len() && scrubbed.as_bytes()[cursor] == b' ' {
                    cursor += 1;
                }
            }
            let value_start = cursor;
            let value_end = advance_to_end_of_value(&scrubbed, value_start);
            scrubbed.replace_range(value_start..value_end, "<redacted>");
            search_from = value_start + "<redacted>".len();
        }
    }
    scrubbed
}

fn advance_to_end_of_value(s: &str, start: usize) -> usize {
    let bytes = s.as_bytes();
    if start >= bytes.len() {
        return start;
    }
    let first = bytes[start];
    if first == b'"' || first == b'\'' {
        let quote = first;
        let mut i = start + 1;
        while i < bytes.len() {
            if bytes[i] == b'\\' && i + 1 < bytes.len() {
                i += 2;
                continue;
            }
            if bytes[i] == quote {
                return i + 1;
            }
            i += 1;
        }
        return bytes.len();
    }
    let mut i = start;
    while i < bytes.len() {
        match bytes[i] {
            b' ' | b'\t' | b'\n' | b'\r' | b',' | b';' | b'}' | b']' => break,
            _ => i += 1,
        }
    }
    i
}

// ---------------------------------------------------------------------------
// Tests live in `tests/error_test.rs`.
// ---------------------------------------------------------------------------
#[cfg(test)]
mod inline_tests {
    use super::*;

    #[test]
    fn scrub_redacts_token_in_value() {
        let out = scrub("GITHUB_TOKEN=ghp_xyz");
        assert!(out.contains("<redacted>"));
        assert!(!out.contains("ghp_xyz"));
    }

    #[test]
    fn scrub_leaves_unrelated_strings_intact() {
        assert_eq!(scrub("hello world"), "hello world");
    }
}
