//! Typed error hierarchy for the daemon.
//!
//! [`CaduceusError`] is the canonical cross-cutting error type. It is
//! re-exported from `lib.rs` and used by every module. The variant
//! set and the field semantics are pinned by `CONTRACTS.md`
//! "Error contract".
//!
//! [`VoiceError`] is a separate type used by the public-voice
//! validator (Task 6.6). It is intentionally separate from
//! [`CaduceusError`] because the voice validator runs *before* the
//! corresponding API mutation and needs to surface a precise
//! reason; mixing the two would lose that distinction.
//!
//! `Debug` is wired through [`scrub`] so a resolved token can never
//! appear in a panic message, log line, or test failure. Callers
//! must pre-scrub before constructing an error variant — the
//! type's invariant is "no resolved token in any string field".

use std::fmt;
use std::path::PathBuf;

/// All Caduceus errors. The variant set is normative; new errors
/// always go through a `CaduceusError` constructor, never a panic on
/// external data.
///
/// `Debug` is wired through [`scrub`] so a resolved token can never
/// appear in user-visible output. `Display` is generated by
/// thiserror and renders variant fields verbatim — callers must
/// scrub before constructing. The daemon's structured logger and
/// the public-voice validator both pass through `Debug` only.
#[derive(thiserror::Error)]
pub enum CaduceusError {
    #[error("caduceus configuration error: {0}")]
    Config(String),

    #[error(transparent)]
    Io(#[from] std::io::Error),

    #[error(transparent)]
    Json(#[from] serde_json::Error),

    #[error(transparent)]
    Yaml(#[from] serde_yaml::Error),

    #[error(transparent)]
    Http(#[from] reqwest::Error),

    /// Git subprocess failure. The ``operation`` is a short stable
    /// identifier (e.g. ``"commit"``, ``"push"``); ``stderr`` carries
    /// the captured stderr text (already redacted by the caller).
    #[error("git {operation} failed: {stderr}")]
    Git {
        operation: &'static str,
        stderr: String,
    },

    /// GitHub API returned a non-success status.
    #[error("GitHub API status {status}: {message}")]
    GitHubApi { status: u16, message: String },

    /// GitHub rate-limit observation. The numeric ``reset_at`` is
    /// the seconds-until-reset reported by the API; ``remaining``
    /// is the request budget left; ``limit`` is the per-window cap
    /// (None when the API omits it).
    #[error("GitHub rate limited; reset in {reset_at}s (remaining {remaining}/{limit:?})")]
    RateLimited {
        reset_at: u64,
        remaining: u32,
        limit: Option<u32>,
    },

    /// Token resolution failure. The wrapped string is a reason
    /// (``"gh not found"``, ``"gh exited 1"``); never the token.
    #[error("failed to resolve a GitHub token: {0}")]
    TokenResolution(String),

    /// Worker supervision failure. ``context`` is a stable operation
    /// label (``"spawn"``, ``"wait"``, ``"signal"``); ``stderr``
    /// carries the captured error text (already redacted).
    #[error("worker supervision failure during {context}: {stderr}")]
    Worker {
        context: &'static str,
        stderr: String,
    },

    /// Worktree creation/teardown failure. ``context`` is a stable
    /// operation label (``"create"``, ``"destroy"``, ``"gc"``);
    /// ``stderr`` carries the captured error text.
    #[error("worktree {context} failure: {stderr}")]
    Worktree {
        context: &'static str,
        stderr: String,
    },

    /// Queue state transition failure. ``context`` is a stable
    /// operation label (``"claim"``, ``"release"``, ``"complete"``).
    #[error("queue {context} failure: {stderr}")]
    Queue {
        context: &'static str,
        stderr: String,
    },

    /// Push subprocess failure. ``context`` is a stable operation
    /// label (``"ls-remote"``, ``"push"``); ``stderr`` carries the
    /// captured error text (already redacted by the caller).
    #[error("push {context} failure: {stderr}")]
    Push {
        context: &'static str,
        stderr: String,
    },

    /// The remote had a non-ancestor ref under the daemon branch
    /// name. The push is rejected without `--force`; the operator
    /// must reconcile the branch manually.
    #[error("push collision on {branch}: remote {remote_oid}, local {local_oid}")]
    PushCollision {
        branch: String,
        remote_oid: String,
        local_oid: String,
    },

    /// State file is corrupt on disk. The path is preserved verbatim
    /// so the operator can quarantine or inspect the file. The
    /// error variant does NOT auto-delete the file — the daemon's
    /// contract preserves corruption for diagnosis.
    #[error("corrupt state file at {}: {message}", path.display())]
    StateCorrupt { path: PathBuf, message: String },

    /// Reconciliation of an external side effect failed: the
    /// remote marker disagrees with the local checkpoint. The
    /// operator must inspect the run and resolve the conflict.
    #[error("reconciliation failed for {stage}: {details}")]
    ReconciliationFailed { stage: String, details: String },

    /// A conflicting remote marker was found during
    /// reconciliation. The generation transitions to
    /// `NeedsAttention` so the operator can inspect and
    /// resolve.
    #[error("conflicting remote marker for {stage}: expected {expected}, found {actual}")]
    ConflictingMarker {
        stage: String,
        expected: String,
        actual: String,
    },

    /// Scheduler leadership was contended. The context is a stable
    /// operation label (e.g. ``"acquire"``); stderr carries the
    /// captured error detail.
    #[error("scheduler leadership contended: {context}: {stderr}")]
    LeadershipContended {
        context: &'static str,
        stderr: String,
    },

    /// Lease operation failed because the lease is not held, is
    /// expired, or the caller is not the current owner. The context
    /// is a stable label (e.g. ``"renew"``, ``"release"``); stderr
    /// carries the detail.
    #[error("lease {context} failure: {stderr}")]
    LeaseStale {
        context: &'static str,
        stderr: String,
    },

    /// A mutation was attempted with a fencing token that is lower
    /// than the lease's current token, indicating the caller is a
    /// recovered prior holder whose lease has expired but whose
    /// cached token is stale. The error carries both the stale and
    /// current tokens for diagnostics.
    #[error(
        "fencing token regression for {issue_key}: stale token \
         {stale_token} < current token {current_token}"
    )]
    FencingTokenRegression {
        issue_key: String,
        stale_token: u64,
        current_token: u64,
    },

    #[error("operation cancelled")]
    Cancelled,

    /// The worker pool has no available permits. Current depth
    /// and max depth are surfaced so the caller can decide
    /// whether to retry immediately or route to NeedsAttention.
    #[error("pool saturated: {current_depth}/{max_depth} permits held")]
    PoolSaturated { current_depth: u32, max_depth: u32 },

    /// A per-repository exclusion lock is held by another
    /// admission for the same repo key. The caller should
    /// treat this as a transient infrastructure failure.
    #[error("repository exclusion held: {repo_key}")]
    RepositoryExclusionHeld { repo_key: String },

    /// The drain timeout elapsed before all in-flight workers
    /// completed. The listed run IDs had their leases cancelled.
    #[error("drain timed out for run(s): {timed_out_run_ids:?}")]
    DrainTimeout { timed_out_run_ids: Vec<String> },

    /// The circuit is open for the given scope and scope_id.
    /// `retry_after` is the number of seconds until the circuit
    /// transitions to half-open for a probe.
    #[error("circuit open for {scope}:{scope_id}, retry after {retry_after}s (probe_in_flight={probe_in_flight})")]
    CircuitOpen {
        scope: &'static str,
        scope_id: String,
        retry_after: i64,
        probe_in_flight: bool,
    },

    /// The circuit has been open longer than the max degraded age.
    /// The associated work must transition to NeedsAttention.
    #[error("max degraded age exceeded for {scope}:{scope_id}, opened at {opened_at}")]
    MaxDegradedAgeExceeded {
        scope: &'static str,
        scope_id: String,
        opened_at: i64,
    },

    /// The storage root (or a controlled subdirectory) is a
    /// symlink. The daemon refuses to operate on symlinked
    /// storage to prevent TOCTOU escapes.
    #[error("storage root is a symlink: {}", path.display())]
    SymlinkedStorageRoot { path: PathBuf },

    /// A worktree from a previous failed attempt was found at the
    /// requested path. The daemon refuses to reuse a worktree
    /// whose prior lifecycle was not cleanly completed.
    #[error(
        "reuse of failed worktree {run_id} at {}: last state {last_state}",
        worktree_path.display()
    )]
    WorktreeReuseAfterFailure {
        run_id: String,
        worktree_path: PathBuf,
        last_state: String,
    },

    /// A filesystem mode check did not match the expected
    /// permissions. The expected and observed modes are shown in
    /// octal.
    #[error(
        "mode not preserved at {}: expected {expected:o}, observed {observed:o}",
        path.display()
    )]
    ModeNotPreserved {
        path: PathBuf,
        expected: u32,
        observed: u32,
    },

    /// The configured OCI CLI binary was not found in PATH.
    #[error("OCI CLI not found: {cli}")]
    OciCliNotFound { cli: String },

    /// The OCI engine (Docker/Podman daemon) is not reachable.
    #[error("OCI engine unavailable: {detail}")]
    OciEngineUnavailable { detail: String },

    /// The OCI CLI version is incompatible with the daemon's contract.
    #[error("OCI CLI version mismatch: {detail}")]
    OciMismatchedCliVersion { detail: String },

    /// Image pull failed.
    #[error("OCI pull failed for {image}: {stderr}")]
    OciPullFailed { image: String, stderr: String },

    /// Container create step failed.
    #[error("OCI create failed: {context}: {stderr}")]
    OciCreateFailed {
        context: &'static str,
        stderr: String,
    },

    /// Container start step failed.
    #[error("OCI start failed: {context}: {stderr}")]
    OciStartFailed {
        context: &'static str,
        stderr: String,
    },

    /// Container wait step failed.
    #[error("OCI wait failed: {context}: {stderr}")]
    OciWaitFailed {
        context: &'static str,
        stderr: String,
    },

    /// Container stop step failed.
    #[error("OCI stop failed: {context}: {stderr}")]
    OciStopFailed {
        context: &'static str,
        stderr: String,
    },

    /// Container remove step failed.
    #[error("OCI remove failed: {context}: {stderr}")]
    OciRemoveFailed {
        context: &'static str,
        stderr: String,
    },

    /// A mount path not in the declared allow-list was requested.
    #[error("OCI undeclared mount: {path}")]
    OciUndeclaredMount { path: String },

    /// A potential secret leak was detected in OCI output.
    #[error("OCI secret leak suspected at {path}")]
    OciSecretLeakSuspected { path: String },

    /// A secret value was found in OCI output after the container
    /// completed. This is a confirmed leak, not a suspicion.
    #[error("OCI secret leak detected in output for {run_id}")]
    OciSecretLeakDetected { run_id: String },

    /// Trusted-host execution was selected but the operator has not
    /// explicitly acknowledged reduced containment. This fires at
    /// `Config::load` BEFORE any subprocess is spawned, so a daemon
    /// that fails this check never starts the worker.
    #[error("trusted-host execution requires reduced_containment_acknowledged: true in config")]
    ReducedContainmentNotAcknowledged,

    /// A network profile referenced in the run spec was not found in
    /// the configured allow-list.
    #[error("OCI network profile not in configured profiles: {profile}")]
    OciNetworkNotInProfile { profile: String },

    /// A secret was requested but is not in the configured grant list.
    #[error("OCI secret not granted: {name}")]
    OciSecretNotGranted { name: String },

    /// An image reference is tag-only (not pinned by digest).
    #[error("OCI image is not digest-pinned: {reference}")]
    OciImageNotDigestPinned { reference: String },

    /// A required resource limit (CPU, memory, or PIDs) was not set.
    #[error("OCI resource limit required: {resource}")]
    OciResourceLimitRequired { resource: &'static str },

    /// A baseline policy check failed (e.g., engine socket mount detected).
    #[error("OCI baseline violation: {detail}")]
    OciBaselineViolation { detail: String },

    /// No upgrade choice has been persisted for the daemon.
    #[error("OCI upgrade choice is required before running in OCI mode")]
    OciUpgradeChoiceRequired,

    /// Pull policy `Always` is incompatible with digest-pinned images.
    #[error("OCI pull policy incompatible: {detail}")]
    OciPullPolicyIncompatible { detail: String },

    #[error("{0}")]
    Other(String),
}

/// Canonical `Result` alias used everywhere in the daemon.
pub type CaduceusResult<T> = Result<T, CaduceusError>;

impl fmt::Debug for CaduceusError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // Render via Display, scrubbed through the redaction helper.
        // This keeps the contract guarantee: Debug never contains
        // a resolved token.
        let rendered = match self {
            CaduceusError::Config(s) => format!("Config({})", scrub(s)),
            CaduceusError::Io(err) => format!("Io({})", scrub(&err.to_string())),
            CaduceusError::Json(err) => format!("Json({})", scrub(&err.to_string())),
            CaduceusError::Yaml(err) => format!("Yaml({})", scrub(&err.to_string())),
            CaduceusError::Http(err) => format!("Http({})", scrub(&err.to_string())),
            CaduceusError::Git { operation, stderr } => {
                format!(
                    "Git {{ operation: {:?}, stderr: {} }}",
                    operation,
                    scrub(stderr)
                )
            }
            CaduceusError::GitHubApi { status, message } => format!(
                "GitHubApi {{ status: {status}, message: {} }}",
                scrub(message)
            ),
            CaduceusError::RateLimited {
                reset_at,
                remaining,
                limit,
            } => format!(
                "RateLimited {{ reset_at: {reset_at}, remaining: {remaining}, limit: {limit:?} }}"
            ),
            CaduceusError::TokenResolution(s) => {
                format!("TokenResolution({})", scrub(s))
            }
            CaduceusError::Worker { context, stderr } => format!(
                "Worker {{ context: {:?}, stderr: {} }}",
                context,
                scrub(stderr)
            ),
            CaduceusError::Worktree { context, stderr } => format!(
                "Worktree {{ context: {:?}, stderr: {} }}",
                context,
                scrub(stderr)
            ),
            CaduceusError::Queue { context, stderr } => format!(
                "Queue {{ context: {:?}, stderr: {} }}",
                context,
                scrub(stderr)
            ),
            CaduceusError::Push { context, stderr } => format!(
                "Push {{ context: {:?}, stderr: {} }}",
                context,
                scrub(stderr)
            ),
            CaduceusError::PushCollision {
                branch,
                remote_oid,
                local_oid,
            } => format!(
                "PushCollision {{ branch: {:?}, remote_oid: {:?}, local_oid: {:?} }}",
                branch, remote_oid, local_oid
            ),
            CaduceusError::StateCorrupt { path, message } => format!(
                "StateCorrupt {{ path: {:?}, message: {} }}",
                path,
                scrub(message)
            ),
            CaduceusError::ReconciliationFailed { stage, details } => format!(
                "ReconciliationFailed {{ stage: {:?}, details: {} }}",
                stage,
                scrub(details)
            ),
            CaduceusError::ConflictingMarker {
                stage,
                expected,
                actual,
            } => format!(
                "ConflictingMarker {{ stage: {:?}, expected: {:?}, actual: {:?} }}",
                stage, expected, actual
            ),
            CaduceusError::LeadershipContended { context, stderr } => format!(
                "LeadershipContended {{ context: {:?}, stderr: {} }}",
                context,
                scrub(stderr)
            ),
            CaduceusError::LeaseStale { context, stderr } => format!(
                "LeaseStale {{ context: {:?}, stderr: {} }}",
                context,
                scrub(stderr)
            ),
            CaduceusError::FencingTokenRegression {
                issue_key,
                stale_token,
                current_token,
            } => format!(
                "FencingTokenRegression {{ issue_key: {:?}, stale_token: {}, current_token: {} }}",
                issue_key, stale_token, current_token
            ),
            CaduceusError::Cancelled => "Cancelled".to_string(),
            CaduceusError::PoolSaturated {
                current_depth,
                max_depth,
            } => format!(
                "PoolSaturated {{ current_depth: {}, max_depth: {} }}",
                current_depth, max_depth
            ),
            CaduceusError::RepositoryExclusionHeld { repo_key } => {
                format!("RepositoryExclusionHeld {{ repo_key: {:?} }}", repo_key)
            }
            CaduceusError::DrainTimeout { timed_out_run_ids } => format!(
                "DrainTimeout {{ timed_out_run_ids: {:?} }}",
                timed_out_run_ids
            ),
            CaduceusError::CircuitOpen {
                scope,
                scope_id,
                retry_after,
                probe_in_flight,
            } => format!(
                "CircuitOpen {{ scope: {:?}, scope_id: {:?}, retry_after: {}, probe_in_flight: {} }}",
                scope, scope_id, retry_after, probe_in_flight
            ),
            CaduceusError::MaxDegradedAgeExceeded {
                scope,
                scope_id,
                opened_at,
            } => format!(
                "MaxDegradedAgeExceeded {{ scope: {:?}, scope_id: {:?}, opened_at: {} }}",
                scope, scope_id, opened_at
            ),
            CaduceusError::SymlinkedStorageRoot { path } => {
                format!("SymlinkedStorageRoot {{ path: {:?} }}", path)
            }
            CaduceusError::WorktreeReuseAfterFailure {
                run_id,
                worktree_path,
                last_state,
            } => format!(
                "WorktreeReuseAfterFailure {{ run_id: {:?}, worktree_path: {:?}, last_state: {} }}",
                run_id,
                worktree_path,
                scrub(last_state)
            ),
            CaduceusError::ModeNotPreserved {
                path,
                expected,
                observed,
            } => format!(
                "ModeNotPreserved {{ path: {:?}, expected: {:o}, observed: {:o} }}",
                path, expected, observed
            ),
            CaduceusError::OciCliNotFound { cli } => {
  format!("OciCliNotFound {{ cli: {:?} }}", cli)
  }
  CaduceusError::OciEngineUnavailable { detail } => {
  format!("OciEngineUnavailable {{ detail: {} }}", scrub(detail))
  }
  CaduceusError::OciMismatchedCliVersion { detail } => {
  format!("OciMismatchedCliVersion {{ detail: {} }}", scrub(detail))
  }
  CaduceusError::OciPullFailed { image, stderr } => format!(
  "OciPullFailed {{ image: {:?}, stderr: {} }}",
  image,
  scrub(stderr)
  ),
  CaduceusError::OciCreateFailed { context, stderr } => {
  format!(
  "OciCreateFailed {{ context: {:?}, stderr: {} }}",
  context,
  scrub(stderr)
  )
  }
  CaduceusError::OciStartFailed { context, stderr } => {
  format!(
  "OciStartFailed {{ context: {:?}, stderr: {} }}",
  context,
  scrub(stderr)
  )
  }
  CaduceusError::OciWaitFailed { context, stderr } => {
  format!(
  "OciWaitFailed {{ context: {:?}, stderr: {} }}",
  context,
  scrub(stderr)
  )
  }
  CaduceusError::OciStopFailed { context, stderr } => {
  format!(
  "OciStopFailed {{ context: {:?}, stderr: {} }}",
  context,
  scrub(stderr)
  )
  }
  CaduceusError::OciRemoveFailed { context, stderr } => {
  format!(
  "OciRemoveFailed {{ context: {:?}, stderr: {} }}",
  context,
  scrub(stderr)
  )
  }
  CaduceusError::OciUndeclaredMount { path } => {
  format!("OciUndeclaredMount {{ path: {:?} }}", path)
  }
  CaduceusError::OciSecretLeakSuspected { path } => {
  format!("OciSecretLeakSuspected {{ path: {:?} }}", path)
  }
  CaduceusError::OciSecretLeakDetected { run_id } => {
  format!("OciSecretLeakDetected {{ run_id: {:?} }}", run_id)
  }
            CaduceusError::ReducedContainmentNotAcknowledged => {
                "ReducedContainmentNotAcknowledged".to_string()
            }
            CaduceusError::OciNetworkNotInProfile { profile } => {
                format!("OciNetworkNotInProfile {{ profile: {:?} }}", profile)
            }
            CaduceusError::OciSecretNotGranted { name } => {
                format!("OciSecretNotGranted {{ name: {:?} }}", name)
            }
            CaduceusError::OciImageNotDigestPinned { reference } => {
                format!("OciImageNotDigestPinned {{ reference: {:?} }}", reference)
            }
            CaduceusError::OciResourceLimitRequired { resource } => {
                format!("OciResourceLimitRequired {{ resource: {:?} }}", resource)
            }
            CaduceusError::OciBaselineViolation { detail } => {
                format!("OciBaselineViolation {{ detail: {} }}", scrub(detail))
            }
            CaduceusError::OciUpgradeChoiceRequired => {
                "OciUpgradeChoiceRequired".to_string()
            }
            CaduceusError::OciPullPolicyIncompatible { detail } => {
                format!("OciPullPolicyIncompatible {{ detail: {} }}", scrub(detail))
            }
            CaduceusError::Other(s) => format!("Other({})", scrub(s)),
        };
        f.write_str(&rendered)
    }
}

impl CaduceusError {
    /// Wrap a non-token error message in `Other(String)`. This is
    /// the only public constructor that doesn't already have a
    /// variant; callers should prefer the typed variants.
    pub fn other<S: Into<String>>(message: S) -> Self {
        CaduceusError::Other(message.into())
    }

    /// Map a daemon error to the process exit code announced in
    /// `CONTRACTS.md` "CLI contract".
    ///
    /// `run` returns 0 for processed/idle/concurrent/cadence/
    /// rate-limit/cancelled outcomes and 1 for configuration,
    /// corruption, invariant, or unrecovered pipeline failures.
    /// `status` returns 2 for missing state and 1 for corrupt
    /// state. The CLI host code is responsible for selecting the
    /// right exit-code policy per command.
    pub fn exit_code(&self) -> std::process::ExitCode {
        use std::process::ExitCode;
        match self {
            CaduceusError::Cancelled => ExitCode::from(0),
            CaduceusError::RateLimited { .. } => ExitCode::from(0),
            _ => ExitCode::from(1),
        }
    }
}

// ---------------------------------------------------------------------------
// Voice errors
// ---------------------------------------------------------------------------

/// Errors produced by the public-voice validator (Task 6.6). Kept
/// separate from [`CaduceusError`] so the validator can run before
/// a corresponding API mutation has been attempted and report a
/// precise reason without conflating with daemon-wide errors.
#[derive(Clone, Debug, Eq, PartialEq, thiserror::Error)]
pub enum VoiceError {
    /// A configured forbidden term was found in the outbound text.
    /// The first match is captured — operators see *which* term
    /// was matched so they can update the allowlist.
    #[error("voice: forbidden term matched: {found:?}")]
    Forbidden { found: String },

    /// The outbound text exceeds the documented size limit for the
    /// channel (PR body, comment, etc.).
    #[error("voice: text exceeds limit of {limit} bytes")]
    TooLong { limit: usize },
}

impl VoiceError {
    /// True when the error is purely about the text content; the
    /// daemon can suppress retry on these and ask the operator to
    /// adjust the source text.
    pub fn is_terminal(&self) -> bool {
        match self {
            VoiceError::Forbidden { .. } => true,
            VoiceError::TooLong { .. } => true,
        }
    }
}

// ---------------------------------------------------------------------------
// Lossless conversions
// ---------------------------------------------------------------------------

impl From<std::path::StripPrefixError> for CaduceusError {
    fn from(_: std::path::StripPrefixError) -> Self {
        CaduceusError::Other("strip prefix failed".to_string())
    }
}

// `From<tokio::task::JoinError>` etc. would be added here as the
// runtime grows. Only conversions that lose no information about the
// underlying cause land in this impl block.

impl From<std::num::ParseIntError> for CaduceusError {
    fn from(err: std::num::ParseIntError) -> Self {
        CaduceusError::Other(format!("parse int: {err}"))
    }
}

// ---------------------------------------------------------------------------
// Redaction helper
// ---------------------------------------------------------------------------

/// Replace recognised credential names with `<redacted>` so the
/// returned string is safe to render through `Debug` (and any
/// downstream `tracing` panic message or test failure message).
///
/// The deny-list mirrors the worker-env-allowlist contract: the
/// three canonical credential variables and any prefix wildcard
/// that would expose them. The function is intentionally a
/// standalone helper so every error path that wants to surface a
/// string can apply it.
pub fn scrub(value: &str) -> String {
    if value.is_empty() {
        return value.to_string();
    }
    let mut scrubbed = value.to_string();
    for needle in ["GITHUB_TOKEN", "CADUCEUS_GITHUB_TOKEN", "GH_TOKEN"] {
        let mut search_from = 0usize;
        while let Some(pos) = scrubbed[search_from..].find(needle) {
            let abs = search_from + pos;
            // Boundary check on the left so ``MY_GITHUB_TOKEN`` is
            // not matched.
            if abs > 0 {
                let prev = scrubbed.as_bytes()[abs - 1];
                if prev.is_ascii_alphanumeric() || prev == b'_' {
                    search_from = abs + needle.len();
                    continue;
                }
            }
            let after = abs + needle.len();
            let mut cursor = after;
            while cursor < scrubbed.len() && scrubbed.as_bytes()[cursor] == b' ' {
                cursor += 1;
            }
            if cursor < scrubbed.len() && scrubbed.as_bytes()[cursor] == b'=' {
                cursor += 1;
                while cursor < scrubbed.len() && scrubbed.as_bytes()[cursor] == b' ' {
                    cursor += 1;
                }
            }
            let value_start = cursor;
            let value_end = advance_to_end_of_value(&scrubbed, value_start);
            scrubbed.replace_range(value_start..value_end, "<redacted>");
            search_from = value_start + "<redacted>".len();
        }
    }
    scrubbed
}

fn advance_to_end_of_value(s: &str, start: usize) -> usize {
    let bytes = s.as_bytes();
    if start >= bytes.len() {
        return start;
    }
    let first = bytes[start];
    if first == b'"' || first == b'\'' {
        let quote = first;
        let mut i = start + 1;
        while i < bytes.len() {
            if bytes[i] == b'\\' && i + 1 < bytes.len() {
                i += 2;
                continue;
            }
            if bytes[i] == quote {
                return i + 1;
            }
            i += 1;
        }
        return bytes.len();
    }
    let mut i = start;
    while i < bytes.len() {
        match bytes[i] {
            b' ' | b'\t' | b'\n' | b'\r' | b',' | b';' | b'}' | b']' => break,
            _ => i += 1,
        }
    }
    i
}

// ---------------------------------------------------------------------------
// Tests live in `tests/state/error_test.rs`.
// ---------------------------------------------------------------------------
#[cfg(test)]
mod inline_tests {
    use super::*;

    #[test]
    fn scrub_redacts_token_in_value() {
        let out = scrub("GITHUB_TOKEN=ghp_xyz");
        assert!(out.contains("<redacted>"));
        assert!(!out.contains("ghp_xyz"));
    }

    #[test]
    fn scrub_leaves_unrelated_strings_intact() {
        assert_eq!(scrub("hello world"), "hello world");
    }
}
